studio/core/urls.py
from django.urls import path

from . import views

app_name='core'

urlpatterns=[
    path('',views.index,name='index'),
    path('about/',views.about,name='about')
]

studio/studio/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('',include('account.urls')),
    path('projects/',include('project.urls')),
    path('projects/<uuid:project_id>/',include('todolist.urls')),
]

studio/todolist/urls.py
from django.urls import path

from . import views

app_name='todolist'

urlpatterns=[
    path('add/',views.add_todo,name='add_todo'),
    path('<uuid:pk>/',views.detail,name='detail'),
    path('<uuid:pk>/edit/',views.edit,name='edit'),
    ]

studio/todolist/models.py
from django.db import models

# Create your models here.
import uuid

from account.models import User
from project.models import Project

class Todo(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False)    
    name=models.CharField(max_length=255)
    description=models.TextField(blank=True,null=True)
    created_by=models.ForeignKey(User,related_name='todolists',on_delete=models.CASCADE)
    project=models.ForeignKey(Project,related_name='todolists',on_delete=models.CASCADE)


    def __str__(self):
        return f"{self.name} - {self.description}"
        

studio/todolist/views.py
from django.shortcuts import render,redirect

from django.contrib.auth.decorators import login_required

# Create your views here.

from .models import Todo
from project.models import Project

@login_required
def add_todo(request,project_id):
    project=Project.objects.filter(created_by=request.user).get(pk=project_id)


    if request.method=='POST':
        name=request.POST.get('name','')
        description=request.POST.get('description','')

        if name:
            Todo.objects.create(project=project,name=name,description=description,created_by=request.user)

            return redirect(f'/projects/{project_id}/')
    return render(request,'todolist/add.html',{
        'project':project
    })

# def todos(request,project_id):
#     todos=Todo.objects.filter(project_id=project_id)

#     return render(request,'')

def detail(request,project_id,pk):
    project=Project.objects.filter(created_by=request.user).get(pk=project_id)
    todo=Todo.objects.filter(project=project).get(pk=pk)


    return render(request,'todolist/detail.html',{
        'todo':todo,
        'project':project
    })


def edit(request,project_id,pk):
    project=Project.objects.filter(created_by=request.user).get(pk=project_id)
    todo=Todo.objects.filter(project=project).get(pk=pk)

    return render(request,'todolist/edit.html/',{
            'project':project,
            'todo':todo
        })


    # if request.method=='POST':
    #     name=request.POST.get('name','')
    #     description=request.POST.get('description','')

    #     if name:
    #         todo.name=name
    #         todo.description=description
    #         todo.save()

    #         return redirect('todolist/detail.html/')
        

studio/todolist/templates/todolist/add.html
{% extends 'core/base.html' %} {% block content %}

<h1 class="mb-6 text-3xl">Add Todo</h1>

<div class="max-w-5xl mx-auto py-8 bg-slate-800 text-center">
  <h1 class="text-3xl text-white">Todo</h1>

  <form class="mt-6 px-8 space-y-4" method="POST" action=".">
    {% csrf_token %}
    <div>
      <label class="text-white">Todo_Name</label><br />
      <input
        name="name"
        type="text"
        class="w-full py-4 px-6 bg-slate-500 text-white"
      />
    </div>

    <div>
      <label class="text-white">Todo_Description</label><br />
      <textarea
        name="description"
        type="text"
        class="w-full py-4 px-6 bg-slate-500 text-white"
      ></textarea>
    </div>
    <div>
      <button class="py-4 px-8 bg-sky-600 text-white">Submit</button>
    </div>
  </form>
</div>

{% endblock %}

studio/todolist/templates/todolist/detail.html
{% extends 'core/base.html' %} {% block content %}
<h1 class="mb-6 text-3xl">{{todo.name}}</h1>
{% if todo.description %}
<h1 class="text-lg">{{todo.description}}</h1>
<br />
{% endif %}

<a href="#" class="py-4 px-8 bg-sky-600 text-white inline-block"> Add task </a>

<a
  href="{% url 'todolist:edit' project.id todo.id %}"
  class="py-4 px-8 bg-sky-600 text-white inline-block"
>
  Edit
</a>

<a href="#" class="py-4 px-8 bg-sky-600 text-white inline-block"> Delete </a>

<div class="mt-6 grid grid-cols-4 gap-4">
  {% for task in todolist.task.all%}
  <div class="py-6 px-6 bg-slate-200 mb-4 rounded-lg shadow-md relative">
    <a href="#">
      <h2 class="mb-2 text-xl font-semibold">{{ task.name }}</h2>
      <p class="text-sm text-slate-600">{{ task.description }}</p>
    </a>
  </div>
  {% endfor %}
</div>

{% endblock %}

studio/todolist/templates/todolist/edit.html
{% extends 'core/base.html' %} {% block content %}

<h1 class="mb-6 text-3xl">Edit Todo</h1>

<div class="max-w-5xl mx-auto py-8 bg-slate-800 text-center">
  <h1 class="text-3xl text-white">Todo</h1>

  <form class="mt-6 px-8 space-y-4" method="POST" action=".">
    {% csrf_token %}
    <div>
      <label class="text-white">Name</label><br />
      <input
        name="name"
        type="text"
        class="w-full py-4 px-6 bg-slate-500 text-white"
      />
    </div>

    <div>
      <label class="text-white">Description</label><br />
      <textarea
        name="description"
        type="text"
        class="w-full py-4 px-6 bg-slate-500 text-white"
      ></textarea>
    </div>
    <div>
      <button class="py-4 px-8 bg-sky-600 text-white">Submit</button>
    </div>
  </form>
</div>

{% endblock %}