studio/core/urls.py
from django.urls import path

from . import views

app_name='core'

urlpatterns=[
    path('',views.index,name='index'),
    path('about/',views.about,name='about')
]

studio/project/urls.py
from django.urls import path

from . import views

app_name='project'

urlpatterns=[
    path('',views.projects,name='projects'),
    path('add/',views.add_project,name='add'),
    path('<uuid:pk>/',views.project,name='project'),
    path('<uuid:pk>/edit/',views.edit_proejct,name='edit_project'),
    path('<uuid:project_id>/delete/',views.delete_project,name='delete_project'),
]

studio/studio/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('',include('account.urls')),
    path('projects/',include('project.urls')),
    path('projects/<uuid:project_id>/',include('todolist.urls')),
]

studio/todolist/urls.py
from django.urls import path

from . import views

app_name='todolist'

urlpatterns=[
    path('add/',views.add_todo,name='add_todo'),
    path('<uuid:pk>/',views.detail,name='detail'),
    path('<uuid:pk>/edit/',views.edit,name='edit'),
    ]

studio/project/models.py
from django.db import models

# Create your models here.
import uuid

from account.models import User

class Project(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False)    
    name=models.CharField(max_length=255)
    description=models.TextField(blank=True,null=True)
    created_by=models.ForeignKey(User,related_name='projects',on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.description}"
        

studio/project/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Project
from todolist.models import Todo

# Create your views here.

@login_required
def projects(request):
    projects=Project.objects.filter(created_by=request.user)
    return render(request,'project/projects.html',{
        'my_projects':projects
    })


@login_required
def add_project(request):
    if request.method=="POST":
        name=request.POST.get('name','')
        description=request.POST.get('description','')
        if name:
            print(description)
            project=Project.objects.create(name=name,description=description,created_by=request.user)
            return redirect('/projects')
        else:
            print('Not Valid')
    else:
        print("not entered")

    return render(request,'project/add.html')




@login_required
def delete_project(request,project_id):
    project=get_object_or_404(Project,id=project_id)

    project.delete()

    return redirect('/projects/')


@login_required
def project(request,pk):
    project=Project.objects.filter(created_by=request.user).get(pk=pk)

    return render(request,'project/project.html',{
        'project':project
    })

@login_required
def edit_proejct(request,pk):
    project=Project.objects.filter(created_by=request.user).get(pk=pk)

    if request.method=='POST':
        name=request.POST.get('name','')
        description=request.POST.get('description','')

        if name:
            project.name=name
            project.description=description
            project.save()

            return redirect('/projects/')
    
    return render(request,'project/edit.html',{
        'project':project
    })

studio/project/templates/project/add.html
{% extends 'core/base.html' %} {% block content %}

<h1 class="mb-6 text-3xl">Add projects</h1>

<div class="max-w-5xl mx-auto py-8 bg-slate-800 text-center">
  <h1 class="text-3xl text-white">Project</h1>

  <form class="mt-6 px-8 space-y-4" method="POST" action=".">
    {% csrf_token %}
    <div>
      <label class="text-white">Name</label><br />
      <input
        name="name"
        type="text"
        class="w-full py-4 px-6 bg-slate-500 text-white"
      />
    </div>

    <div>
      <label class="text-white">Description</label><br />
      <textarea
        name="description"
        type="text"
        class="w-full py-4 px-6 bg-slate-500 text-white"
      ></textarea>
    </div>
    <div>
      <button class="py-4 px-8 bg-sky-600 text-white">Submit</button>
    </div>
  </form>
</div>

{% endblock %}

studio/project/templates/project/edit.html
{% extends 'core/base.html' %} {% block content %}

<h1 class="mb-6 text-3xl">Edit Project</h1>

<div class="max-w-5xl mx-auto py-8 bg-slate-800 text-center">
  <h1 class="text-3xl text-white">Project</h1>

  <form class="mt-6 px-8 space-y-4" method="POST" action=".">
    {% csrf_token %}
    <div>
      <label class="text-white">Name</label><br />
      <input
        name="name"
        type="text"
        class="w-full py-4 px-6 bg-slate-500 text-white"
      />
    </div>

    <div>
      <label class="text-white">Description</label><br />
      <textarea
        name="description"
        type="text"
        class="w-full py-4 px-6 bg-slate-500 text-white"
      ></textarea>
    </div>
    <div>
      <button class="py-4 px-8 bg-sky-600 text-white">Submit</button>
    </div>
  </form>
</div>

{% endblock %}

studio/project/templates/project/project.html
{% extends 'core/base.html' %} {% block content %}
<h1 class="mb-6 text-3xl">{{project.name}}</h1>

<a
  href="{% url 'todolist:add_todo' project.id %}"
  class="py-4 px-8 bg-sky-600 text-white inline-block"
>
  Add Todolist
</a>

<a
  href="{% url 'project:edit_project' project.id %}"
  class="py-4 px-8 bg-sky-600 text-white inline-block"
>
  Edit
</a>

<a
  href="{% url 'project:delete_project' project.id %}"
  class="py-4 px-8 bg-sky-600 text-white inline-block"
>
  Delete
</a>

<div class="mt-6 grid grid-cols-4 gap-4">
  {% for todolist in project.todolists.all%}
  <div class="py-6 px-6 bg-slate-200 mb-4 rounded-lg shadow-md relative">
    <a href="{% url 'todolist:detail' project.id todolist.id %}">
      <h2 class="mb-2 text-xl font-semibold">{{ todolist.name }}</h2>
      <p class="text-sm text-slate-600">{{ todolist.description }}</p>
    </a>
  </div>
  {% endfor %}
</div>

{% endblock %}

studio/project/templates/project/projects.html
{% extends 'core/base.html' %} {% block content %}
<h1 class="mb-6 text-3xl">Projects</h1>

<a
  href="{% url 'project:add' %}"
  class="py-4 px-8 bg-sky-600 text-white inline-block"
>
  Add project
</a>

<div class="mt-6 grid grid-cols-4 gap-4">
  {% for project in my_projects %}
  <div class="py-6 px-6 bg-slate-200 mb-4 rounded-lg shadow-md relative">
    <a href="{% url 'project:project' project.id %}">
      <h2 class="mb-2 text-xl font-semibold">{{ project.name }}</h2>
      <p class="text-sm text-slate-600">{{ project.description }}</p>
    </a>
  </div>
  {% endfor %}
</div>

{% endblock %}